name: How to play mobile games and get paid.
favicon: null
layout_spectrum: 0.734496284974739
typography_spectrum: 0.9631624319590628
title: gameloot
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7970053078606725
  lightness: 0.12215261184610426
  saturation: 0.522585935657844
  rhythmicContrast: 0.20524302427656949
purpose: []
